# Compute a relative path from `from` (a directory) to `to` (a file/dir).
# Uses only base R, works on all platforms.
#' @keywords internal
.rel_path <- function(from, to) {
  from_parts <- strsplit(from, .Platform$file.sep, fixed = TRUE)[[1]]
  to_parts   <- strsplit(to,   .Platform$file.sep, fixed = TRUE)[[1]]

  # find common prefix length
  common <- 0L
  for (i in seq_len(min(length(from_parts), length(to_parts)))) {
    if (from_parts[i] == to_parts[i]) common <- i else break
  }

  up   <- rep("..", length(from_parts) - common)
  down <- to_parts[seq(common + 1L, length(to_parts))]
  rel  <- paste(c(up, down), collapse = .Platform$file.sep)
  if (nchar(rel) == 0) rel <- "."
  rel
}


#' Write a gene list file for i-ADHoRe
#'
#' @param gene_ids Character vector of gene identifiers (no spaces allowed)
#' @param strand Character vector of strand orientations, "+" or "-"
#' @param file Path to output file
#'
#' @return Invisibly returns the file path
#' @export
write_gene_list <- function(gene_ids, strand, file) {
  if (length(gene_ids) != length(strand)) {
    stop("gene_ids and strand must have the same length")
  }
  if (!all(strand %in% c("+", "-"))) {
    stop("strand must contain only '+' or '-'")
  }
  if (any(grepl(" ", gene_ids))) {
    stop("gene identifiers cannot contain spaces")
  }

  lines <- paste0(gene_ids, strand)
  writeLines(lines, file)
  invisible(file)
}


#' Write an i-ADHoRe configuration file
#'
#' @param genomes Named list of genome fragments. Each element is a named
#'   character vector mapping fragment identifiers to gene list file paths.
#'   Example: `list(ath = c("1" = "ath_lists/1.lst", "2" = "ath_lists/2.lst"))`
#' @param blast_table Path to the BLAST table file (tab-separated gene pairs,
#'   or gene-to-family mappings when `table_type = "family"`)
#' @param output_path Directory where i-ADHoRe writes output files
#' @param file Path to write the configuration file
#' @param gap_size Maximum (pseudo-)distance between points in a colinear
#'   cluster. Suggested: 10-40. Default: 30
#' @param cluster_gap Maximum distance between base clusters to be grouped.
#'   Must be >= gap_size. Default: 35
#' @param q_value Minimum r^2 value for linearity of a cluster (0-1).
#'   Suggested: 0.70-0.90. Default: 0.75
#' @param prob_cutoff Maximum probability for a cluster to be generated by
#'   chance. Suggested: 0.001-0.01. Default: 0.001
#' @param anchor_points Minimum number of anchor points per segment.
#'   Suggested: 3-6. Default: 5
#' @param alignment_method Alignment algorithm: "nw", "gg", or "gg2".
#'   Default: "gg2"
#' @param cluster_type Running mode: "colinear", "cloud", or "hybrid".
#'   Default: "colinear"
#' @param table_type Format of the blast_table file: "pairs" for two-column
#'   gene-pair format, or "family" for gene-to-family format. Default: "pairs"
#' @param tandem_gap Maximum Euclidean distance for tandem duplicate detection.
#'   Default: NULL (uses gap_size / 2)
#' @param multiple_hypothesis_correction "FDR", "bonferroni", or "none".
#'   Default: "FDR"
#' @param level_2_only If TRUE, only detect level 2 multiplicons (no profiles).
#'   Default: FALSE
#' @param max_gaps_in_alignment Maximum gaps allowed per segment after
#'   alignment. Default: 20
#' @param number_of_threads Number of threads for parallelisation. Default: 1
#' @param visualize_ghm Write Gene Homology Matrix images. Default: FALSE
#' @param visualize_alignment Write alignment SVG files. Default: FALSE
#' @param write_stats Write supplementary chromosome statistics. Default: FALSE
#' @param verbose_output Print all input parameters to screen. Default: FALSE
#' @param flush_output Number of multiplicons to buffer before writing to disk.
#'   Default: 1000
#' @param cloud_gap_size Maximum Chebyshev distance between dots in a cloud
#'   (cloud/hybrid mode). Default: 20
#' @param cloud_cluster_gap Cloud merging distance threshold
#'   (cloud/hybrid mode). Default: 25
#' @param cloud_filter_method Statistical filter for clouds: "density",
#'   "binomial", or "binomal_corr". Default: "binomial"
#' @param brute_force_syntheny_mode Use exact Chebyshev distances ("on"/"off").
#'   Default: "off"
#'
#' @return Invisibly returns the file path
#' @export
#'
#' @examples
#' \dontrun{
#' # Single species (intra-genomic duplications)
#' write_iadhore_config(
#'   genomes = list(
#'     ath = c("1" = "ath_lists/1.lst", "2" = "ath_lists/2.lst")
#'   ),
#'   blast_table = "families.csv",
#'   output_path = "output/",
#'   file = "config.ini",
#'   table_type = "family"
#' )
#'
#' # Multiple species (inter-genomic synteny)
#' write_iadhore_config(
#'   genomes = list(
#'     ath = c("1" = "ath_lists/1.lst", "2" = "ath_lists/2.lst"),
#'     vvi = c("chr1" = "vvi_lists/chr1.lst", "chr2" = "vvi_lists/chr2.lst")
#'   ),
#'   blast_table = "families.csv",
#'   output_path = "output/",
#'   file = "config.ini",
#'   table_type = "family"
#' )
#' }
write_iadhore_config <- function(
    genomes,
    blast_table,
    output_path,
    file,
    gap_size = 30,
    cluster_gap = 35,
    q_value = 0.75,
    prob_cutoff = 0.001,
    anchor_points = 5,
    alignment_method = "gg2",
    cluster_type = "colinear",
    table_type = "pairs",
    tandem_gap = NULL,
    multiple_hypothesis_correction = "FDR",
    level_2_only = FALSE,
    max_gaps_in_alignment = 20,
    number_of_threads = 1,
    visualize_ghm = FALSE,
    visualize_alignment = FALSE,
    write_stats = FALSE,
    verbose_output = FALSE,
    flush_output = 1000,
    cloud_gap_size = 20,
    cloud_cluster_gap = 25,
    cloud_filter_method = "binomial",
    brute_force_syntheny_mode = "off") {

  alignment_method <- match.arg(alignment_method, c("nw", "gg", "gg2"))
  cluster_type <- match.arg(cluster_type, c("colinear", "cloud", "hybrid"))
  multiple_hypothesis_correction <- match.arg(
    multiple_hypothesis_correction, c("FDR", "bonferroni", "none")
  )

  # i-ADHoRe resolves all paths relative to the working directory it is
  # launched from, which is the config file's directory. Convert all file
  # paths to be relative to that directory.
  config_dir <- normalizePath(dirname(file), mustWork = FALSE)
  if (!dir.exists(config_dir)) dir.create(config_dir, recursive = TRUE)
  # Re-normalize after dir.create so symlinks are resolved (e.g. /Users ->
  # /private/Users on macOS) consistently with how other existing paths resolve.
  config_dir <- normalizePath(config_dir, mustWork = TRUE)

  # Resolve a path by walking up to the deepest existing ancestor so that
  # symlinks in the existing portion are always expanded (mustWork = TRUE),
  # then re-appending the non-existing tail components.
  .resolve_path <- function(path) {
    path  <- normalizePath(path, mustWork = FALSE)
    parts <- character(0)
    p     <- path
    while (!file.exists(p) && p != dirname(p)) {
      parts <- c(basename(p), parts)
      p     <- dirname(p)
    }
    if (length(parts) == 0L) return(normalizePath(p, mustWork = TRUE))
    do.call(file.path, c(list(normalizePath(p, mustWork = TRUE)), as.list(parts)))
  }

  rel <- function(path) {
    .rel_path(config_dir, .resolve_path(path))
  }

  lines <- character(0)

  # genome sections
  for (genome_name in names(genomes)) {
    lines <- c(lines, paste0("genome=", genome_name))
    frags <- genomes[[genome_name]]
    frag_names <- names(frags)
    for (i in seq_along(frags)) {
      lines <- c(lines, paste(frag_names[i], rel(frags[i])))
    }
    lines <- c(lines, "")
  }

  # blast table
  lines <- c(lines, paste0("blast_table=", rel(blast_table)))
  table_type <- match.arg(table_type, c("pairs", "family"))
  lines <- c(lines, paste0("table_type=", table_type))
  lines <- c(lines, "")

  # output path
  lines <- c(lines, paste0("output_path=", rel(output_path)))
  lines <- c(lines, "")

  # running mode
  lines <- c(lines, paste0("cluster_type=", cluster_type))
  lines <- c(lines, "")

  # general parameters
  lines <- c(lines,
    paste0("gap_size=", gap_size),
    paste0("cluster_gap=", cluster_gap),
    paste0("q_value=", q_value),
    paste0("prob_cutoff=", prob_cutoff),
    paste0("anchor_points=", anchor_points),
    paste0("alignment_method=", alignment_method),
    paste0("multiple_hypothesis_correction=", multiple_hypothesis_correction),
    paste0("level_2_only=", tolower(as.character(level_2_only))),
    paste0("max_gaps_in_alignment=", max_gaps_in_alignment)
  )
  if (!is.null(tandem_gap)) {
    lines <- c(lines, paste0("tandem_gap=", tandem_gap))
  }
  lines <- c(lines, "")

  # cloud mode parameters
  if (cluster_type %in% c("cloud", "hybrid")) {
    lines <- c(lines,
      paste0("cloud_gap_size=", cloud_gap_size),
      paste0("cloud_cluster_gap=", cloud_cluster_gap),
      paste0("cloud_filter_method=", cloud_filter_method),
      paste0("bruteForceSynthenyMode=", brute_force_syntheny_mode)
    )
    lines <- c(lines, "")
  }

  # output and parallelization settings
  lines <- c(lines,
    paste0("number_of_threads=", number_of_threads),
    paste0("visualizeGHM=", tolower(as.character(visualize_ghm))),
    paste0("visualizeAlignment=", tolower(as.character(visualize_alignment))),
    paste0("write_stats=", tolower(as.character(write_stats))),
    paste0("verbose_output=", tolower(as.character(verbose_output))),
    paste0("flush_output=", flush_output)
  )

  writeLines(lines, file)
  invisible(file)
}
